exclude: ^(\.vscode/|(.*/)?migrations/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/
      - id: end-of-file-fixer
        exclude: ^tests/
      - id: check-yaml
        exclude: ^tests/
      - id: check-json
        exclude: ^tests/
      - id: check-toml
        exclude: ^tests/
      - id: pretty-format-json
        exclude: ^tests/
        args:
          - --autofix
          - --indent
          - "4"
      - id: check-merge-conflict
        exclude: ^tests/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^tests/
      - id: ruff-format
        # no exclude here -> tests/ IS included

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
        exclude: ^(test.*|src/tests/|tests/|.*migrations/.*)
