[mypy]
exclude = ^(test.*|src/tests/|.*tests/.*|.*migrations/.*|.*/scripts/.*)
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main


[mypy.plugins.django-stubs]
django_settings_module = django_ecommers.config.settings
