line-length = 88
target-version = "py312"

[lint]
exclude = ['src/scripts/]

select = [
    "ALL",
]

ignore = [
    "S104",
    "D100",
    "D104",
    "CPY",
    "D103",
    "D",
    "COM812",
    "TRY",
    "EM",
    "PLC",
    "ANN",
    "F401",
]

[lint.per-file-ignores]
# example: relax rules in tests
"tests/**" = ["S101"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
line-ending = "auto"