# Generated by Django 6.1.1 on 2026-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="hashed_password",
            new_name="password",
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
