# Generated by Django 6.1.1 on 2026-09-12 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_hashed_password_users_password_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="name",
            new_name="username",
        ),
    ]
