# Generated by Django 6.1.1 on 2026-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_name_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
