# Generated by Django 6.1.1 on 2026-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_users_password_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
