# Generated by Django 6.1.1 on 2026-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_addresses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addresses",
            old_name="Users",
            new_name="User",
        ),
    ]
