# Generated by Django 6.1.1 on 2026-10-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_users_addresses_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='User',
            new_name='user',
        ),
    ]
