# Generated by Django 6.1.1 on 2026-09-28 11:26

from django.db import migrations


def create_categories(apps, schema_editor):
    # Important: Use apps.get_model to get the historical model version
    Category = apps.get_model('products', 'Category')
    
    # Define your initial categories
    initial_categories = ['electronic', 'books', 'clothing']
    
    # Create each category
    for category_name in initial_categories:
        Category.objects.get_or_create(name=category_name)


def reverse_categories(apps, schema_editor):
    # Optional: Define how to undo this migration
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(name__in=['electronic', 'books', 'clothing']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_products_category'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_categories),
    ]
