name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:

env:
  DJANGO_SETTINGS_MODULE: django_ecommers.config.settings
  SECRET_KEY: ci-dummy-secret-key
  DJANGO_ENV: development
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASSWORD: mypass
  DB_HOST: localhost
  DB_PORT: "5432"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: format
        run: uv run ruff format .
      - name: Lint
        run: uv run ruff check .
      - name: Type checking
        run: uv run mypy . --show-traceback
      - name: Tests
        run: uv run pytest
      - name: Docker build
        run: Docker build -t django_ecommers .
